services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", ""]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 5s
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: 
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      UPLOAD_DIR: /app/uploads
      SOURCE_IMAGES_DIR: /source_images
      SECRET_KEY: 
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ADMIN_USERS: admin

volumes:
  postgres_data:
